# Generated by Django 5.1.7 on 2025-08-06 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_alter_centre_name_alter_qualificationbranch_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
