# Generated by Django 5.1.7 on 2025-08-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualificationtype',
            name='type',
            field=models.CharField(blank=True, choices=[('Graduation', 'Graduation'), ('Post Graduation', 'Post Graduation'), ('Doctorate', 'Doctorate')], max_length=50, null=True),
        ),
    ]
